### ISSUE TITLE
fix elements which involve [TOE, TOE platform]

### ISSUE THREAD

**Issue by jeffblank** [commoncriteria/emailclient#2]
A lot of the functional elements use the obsolete construction: "The [selection: TSF, TOE platform] shall..."

These need to be reworked into "The email client shall ...".  The element can then state -- only when appropriate -- a selection between [implement, leverage the platform].  (Much of the existing functionality should really only be provided by the email client, so the selection should often not be necessary at all.)

**Comment by japit** [comment]
27 additional references to TSF, TOE platform have been removed. No references to [implement, leverage the platform] have been added.  Update to be pushed today.
