### ISSUE TITLE
remove FIA_X509_EXT.1 , 2 

### ISSUE THREAD

**Issue by jeffblank** [commoncriteria/emailclient#6]
These are now covered in the App PP, right?

Please verify, and then remove.

**Comment by japit** [comment]
Commented out FIA_X509_EXT.1.1, 1.2, .2.1(1), 2.1.(3), and 2.2.  Update to be pushed later today.

**Comment by japit** [comment]
Needs additional discussion.

**Comment by japit** [comment]
Numbering updated in accordance with App PP.  Recommend close.
